export const USERS_REPOSITORY = Symbol('USERS_REPOSITORY');
export const REFRESH_TOKENS_REPOSITORY = Symbol('REFRESH_TOKENS_REPOSITORY');
export const PASSWORD_RESET_TOKENS_REPOSITORY = Symbol(
  'PASSWORD_RESET_TOKENS_REPOSITORY',
);
export const AVAILABILITY_SLOT_REPOSITORY = Symbol(
  'AVAILABILITY_SLOT_REPOSITORY',
);
export const AVAILABILITY_RULES_REPOSITORY = Symbol(
  'AVAILABILITY_RULES_REPOSITORY',
);
export const MENTOR_REPOSITORY = Symbol('MENTOR_REPOSITORY');
